game.AddParticles( "particles/apex_fx.pcf" )
game.AddParticles( "particles/mmod_muzzleflashes.pcf" )
game.AddParticles( "particles/mmod_tracers.pcf" )
game.AddParticles( "particles/mmod_explosions.pcf" )

PrecacheParticleSystem("hl2mmod_generic_tracer")
PrecacheParticleSystem("hl2mmod_tracer_ar2")
PrecacheParticleSystem("hl2mmod_muzzleflash_357")
PrecacheParticleSystem("hl2mmod_muzzleflash_ar2")
PrecacheParticleSystem("hl2mmod_muzzleflash_pistol")
PrecacheParticleSystem("hl2mmod_muzzleflash_shotgun")
PrecacheParticleSystem("hl2mmod_muzzleflash_smg1")

PrecacheParticleSystem("tfa_apex_muzzle_ar")
PrecacheParticleSystem("tfa_apex_muzzle_hmg")
PrecacheParticleSystem("tfa_apex_muzzle_shotgun")
PrecacheParticleSystem("tfa_apex_muzzle_smg")
PrecacheParticleSystem("tfa_apex_muzzle_sniper")
PrecacheParticleSystem("tfa_apex_tracer_anvil")

PrecacheParticleSystem("tfa_apex_energy_tracer_smg") 
PrecacheParticleSystem("tfa_apex_energy_muzzle_big") 
PrecacheParticleSystem("tfa_apex_energy_muzzle_medium")
PrecacheParticleSystem("tfa_apex_energy_muzzle_shotgun")
PrecacheParticleSystem("tfa_apex_havoc_beam_charged")

PrecacheParticleSystem("tfa_apex_energy_tracer_rifle")
PrecacheParticleSystem("tfa_apex_tracer_hmg")
PrecacheParticleSystem("tfa_apex_tracer_pistol")

PrecacheParticleSystem("tfa_apex_tracer_shotgun")
PrecacheParticleSystem("tfa_apex_tracer_smg")
PrecacheParticleSystem("tfa_apex_tracer_sniper")
PrecacheParticleSystem("tfa_apex_tracer_havoc")