game.AddParticles( "particles/apex_fx.pcf" )
game.AddParticles( "particles/mmod_muzzleflashes.pcf" )
game.AddParticles( "particles/mmod_tracers.pcf" )

PrecacheParticleSystem("hl2mmod_generic_tracer")
PrecacheParticleSystem("hl2mmod_tracer_ar2")
PrecacheParticleSystem("hl2mmod_muzzleflash_357")
PrecacheParticleSystem("hl2mmod_muzzleflash_ar2")
PrecacheParticleSystem("hl2mmod_muzzleflash_pistol")
PrecacheParticleSystem("hl2mmod_muzzleflash_shotgun")
PrecacheParticleSystem("hl2mmod_muzzleflash_smg1")

PrecacheParticleSystem("tfa_apex_muzzle_ar")
PrecacheParticleSystem("tfa_apex_muzzle_hmg")
PrecacheParticleSystem("tfa_apex_muzzle_shotty")
PrecacheParticleSystem("tfa_apex_muzzle_smg")
PrecacheParticleSystem("tfa_apex_muzzle_sniper")
PrecacheParticleSystem("tfa_apex_tracer_anvil")

PrecacheParticleSystem("tfa_apex_tracer_ar")
PrecacheParticleSystem("tfa_apex_tracer_energy_hmg")
PrecacheParticleSystem("tfa_apex_tracer_energy_rifle")
PrecacheParticleSystem("tfa_apex_tracer_energy_shotgun")
PrecacheParticleSystem("tfa_apex_tracer_energy_smg")

PrecacheParticleSystem("tfa_apex_tracer_energy_sniper")
PrecacheParticleSystem("tfa_apex_tracer_havoc")
PrecacheParticleSystem("tfa_apex_tracer_hmg")
PrecacheParticleSystem("tfa_apex_tracer_pistol")

PrecacheParticleSystem("tfa_apex_tracer_shotgun")
PrecacheParticleSystem("tfa_apex_tracer_smg")
PrecacheParticleSystem("tfa_apex_tracer_sniper")